/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        //App classUnderTest = new App();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void analyzeWeatherData() {
        App classUnderTest = new App();

        int[][] weeklyMonthTemperatures = {
                {1, 64, 58, 65, 71, 57, 4},
                {57, 45, 65, 70, 72, 65, 51},
                {55, 120, 60, 100, 59, 57, 61}
        };

        assertNotNull("app should return a string", classUnderTest.analyzeWeatherData(weeklyMonthTemperatures));
    }
}
